version: '2'

services:
  nancy_tracker:
    container_name:  nancy_tracker
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - influxDB
  influxDB:
    container_name: influxDB
    image: influxdb:1.8
    restart: 'on-failure'
    volumes:
      - /:/var/lib/docker/volumes/influxdb/_data
    ports:
      - '8086:8086' 
  cadvisor:
    image: zcube/cadvisor:latest
    container_name: cadvisor
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
    devices:
      - /dev/kmsg:/dev/kmsg
    depends_on:
      - ping_monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./monitoring/prometheus:/etc/prometheus:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
     - '9090:9090'
  alertmanager:
    image: prom/alertmanager:v0.23.0
    restart: on-failure
    ports: 
      - '9093:9093'
    volumes:
      - ./alertmanager:/config
    command: --config.file=/config/alertmanager.yml --cluster.advertise-address=0.0.0.0:9093
  discord-alerts:
    image: benjojo/alertmanager-discord
    container_name: discord-alerts
    restart: on-failure
    environment:
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK_URL}