global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs: 
      - targets: ['cadvisor:8080']

  - job_name: 'nancy_tracker'
    static_configs:
      - targets: ['nancy_tracker:5000']